[font]
size = 12.0

[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017" # instead of \x17 or \u{17}

[general]
import = [
	# NOTE: add themes to configure.sh
	"~/alacritty-theme/themes/kanagawa_dragon.toml"
]

# [font.normal]
# family = "JetBrains Mono Nerd Font"
# style = "Regular"

# [font.bold]
# family = "JetBrains Mono Nerd Font"
# style = "Bold"

# [font.italic]
# family = "JetBrains Mono Nerd Font"
# style = "Italic"

# [font.bold_italic]
# family = "JetBrains Mono Nerd Font"
# style = "Bold Italic"
